[tool.poetry]
name = "cheese"
version = "0.1.0"
description = "A cheese index application built with the Django web framework"
authors = ["Kevin Bowen <kevin.bowen@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
cookiecutter = "^1.7.3"
Django = "^3.1.1"
django-environ = "0.4.5"
django-allauth = "0.42.0"
django-model-utils = "4.0.0"
django-crispy-forms = "1.9.2"
django-autoslug = "1.9.8"
pytz = "2022.1"
python-slugify = "6.1.2"
Pillow = "7.2.0"
whitenoise = "5.2.0"
Unidecode = "1.1.1"
Werkzeug = "1.0.1"
ipdb = "0.13.3"
psycopg2-binary = "2.8.6"
friendly = "^0.5.26"
colorama = "^0.4.4"
django-countries = "^7.3.2"

[tool.poetry.dev-dependencies]
flake8 = "3.8.3"
coverage = "5.3"
black = "20.8b1"
pylint-django = "2.3.0"
pre-commit = "2.7.1"
mypy = "0.770"
django-stubs = "1.5.0"
pytest = "6.2.5"
pytest-sugar = "0.9.4"
django-test-plus = "1.4.0"
factory-boy = "3.0.1"
django-debug-toolbar = "3.1"
django-extensions = "3.0.9"
django-coverage-plugin = "1.8.0"
pytest-django = "3.10.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
